#Nginx
nginx:
  image: wonderfall/boring-nginx
  container_name: nginx
  ports:
    - "8000:8000"
    - "4430:4430"
  volumes:
    - /home/%USER%/dockers/nginx/sites-enabled:/sites-enabled
    - /home/%USER%/dockers/nginx/conf:/conf.d
    - /home/%USER%/dockers/nginx/log:/var/log/nginx
    - /home/%USER%/dockers/nginx/certs:/certs
