#Nginx
nginx:
  image: wonderfall/boring-nginx
  container_name: nginx
  ports:
    - "80:8000"
    - "443:4430"
  volumes:
    - /dockers/nginx/sites-enabled:/sites-enabled
    - /dockers/nginx/conf:/conf.d
    - /dockers/nginx/log:/var/log/nginx
    - /dockers/nginx/certs:/certs

#RuTorrent-rTorrent
rutorrent:
  image: diameter/rtorrent-rutorrent
  container_name: rutorrent
  environment:
    - USR_ID=%UID%
    - GRP_ID=%GID%
  ports:
    - "%RUTORRENT_PORT%:80"
    - "49160:49160/udp"
    - "49161:49161"
  volumes:
    - /downloads:/downloads

#Jackett
jackett:
  image : linuxserver/jackett
  container_name: jackett
  environment:
    - PGID=%UID%
    - PUID=%GID%
    - TZ=%TIMEZONE%
  ports:
    - %JACKETT_PORT%:9117
  volumes:
    - /etc/localtime:/etc/locatime:ro
    - /dockers/jackett/downloads:/downloads

#Radarr
radarr:
  image: hotio/radarr
  container_name: radarr
  environment:
    - PUID=%UID%
    - PGID=%GID%
    - TZ=%TIMEZONE%
  ports:
    - %RADARR_PORT%:7878
  links:
    - rutorrent:rutorrent
  volumes:
    - /dockers/radarr/config:/config
    - /movies-downloads:/downloads
    - /movies:/movies

#Sonarr
sonarr:
  image: linuxserver/sonarr
  container_name: sonarr
  environment:
    - PUID=%UID%
    - PGID=%GID%
    - TZ=%TIMEZONE%
  ports:
    - %SONARR_PORT%:8989
  links:
    - rutorrent:rutorrent
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /dockers/sonarr/config:/config
    - /tv-downloads:/downloads
    - /tv:/tv

#UI For Docker
ui-for-docker:
  image: uifd/ui-for-docker
  container_name: ui-for-docker
  ports:
    - %DOCKERUI_PORT%:9000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
