#Nginx
nginx:
  image: wonderfall/boring-nginx
  container_name: nginx
  ports:
    - "80:8000"
    - "443:4430"
  volumes:
    - /dockers/nginx/sites-enabled:/sites-enabled
    - /dockers/nginx/conf:/conf.d
    - /dockers/nginx/log:/var/log/nginx
    - /dockers/nginx/certs:/certs

#RuTorrent-rTorrent
rutorrent:
  image: diameter/rtorrent-rutorrent
  container_name: rutorrent
  environment:
    - USR_ID=0
    - GRP_ID=0
  ports:
    - "1:80"
    - "49160:49160/udp"
    - "49161:49161"
  volumes:
    - /downloads:/downloads

#Jackett
jackett:
  image : linuxserver/jackett
  container_name: jackett
  environment:
    - PGID=0
    - PUID=0
    - TZ=Europe/Paris
  ports:
    - 2:9117
  volumes:
    - /etc/localtime:/etc/locatime:ro
    - /dockers/jackett/downloads:/downloads

#Radarr
radarr:
  image: hotio/radarr
  container_name: radarr
  environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Paris
  ports:
    - 3:7878
  links:
    - rutorrent:rutorrent
  volumes:
    - /dockers/radarr/config:/config
    - /movies-downloads:/downloads
    - /movies:/movies

#Sonarr
sonarr:
  image: linuxserver/sonarr
  container_name: sonarr
  environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Paris
  ports:
    - %SPORT%:8989
  links:
    - rutorrent:rutorrent
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /dockers/sonarr/config:/config
    - /tv-downloads:/downloads
    - /tv:/tv

#UI For Docker
ui-for-docker:
  image: uifd/ui-for-docker
  container_name: ui-for-docker
  ports:
    - 5:9000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true

#Plex
plex:
  image: linuxserver/plex
  container_name: plex
  environment:
    - VERSION=latest
    - PUID=0
    - PGID=0
    - TZ=Europe/Paris
  net: host
  ports:
    - 32400:32400
    - 32400:32400/udp
    - 32469:32469
    - 32469:32469/udp
    - 5353:5353/udp
    - 1900:1900/udp
  volumes:
    - ./dockers/plex/config:/config
    - /tv:/data/tvshows
    - /movies:/data/movies

#Lufi
lufi:
  image: xataz/lufi
  container_name: lufi
  environment:
    - UID=0
    - GID=0
    - WEBROOT=/lufi
    - SECRET=%SECRET%
    - CONTACT=%LUFI_LUTIM_CONTACT%
    - MAX_FILE_SIZE=250000000
  ports:
    - 7:8080
  volumes:
    - ./dockers/lufi/data:/data
    - ./dockers/lufi/files:/files
