#Nginx
nginx:
  image: wonderfall/boring-nginx
  container_name: nginx
  links:
    - postfixadmin:postfixadmin
    - rainloop:rainloop
  ports:
    - "80:8000"
    - "443:4430"
  volumes:
    - ./dockers/nginx/sites-enabled:/sites-enabled
    - ./dockers/nginx/conf:/conf.d
    - ./dockers/nginx/log:/var/log/nginx
    - ./dockers/nginx/certs:/certs

#Fail2Ban
fail2ban:
  image: superitman/fail2ban:latest
  container_name: Fail2Ban
  volumes:
    - ./dockers/fail2ban/filter.d/custom_filter.conf:/etc/fail2ban/filter.d/custom_filter.conf
    - ./dockers/jail.local:/etc/fail2ban/jail.local
    - /var/log:/var/log
  privileged: true

#DBNextcloud
dbnextcloud:
  image: mariadb:10
  container_name: dbnextcloud
  environment:
    - MYSQL_ROOT_PASSWORD=%MYSQL_ROOT_PASSWD%
    - MYSQL_DATABASE=%DB_NEXTCLOUD%
    - MYSQL_USER=%MYSQL_NEXTCLOUD_USER%
    - MYSQL_PASSWORD=%MYSQL_NEXTCLOUD_PASSWD%
  volumes:
    - ./dockers/mariadb/db/nextcloud:/var/lib/mysql

#Nextcloud
nextcloud:
  image: wonderfall/nextcloud:10.0
  container_name: nextcloud
  environment:
    - UID=%UID%
    - GID=%GID%
    - UPLOAD_MAX_SIZE=%UPLOAD_NEXTCLOUD%
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - CRON_PERIOD=15m
    - TZ=Europe/Paris
    - ADMIN_USER=%NEXTCLOUD_ADMIN_USER%
    - ADMIN_PASSWORD=%NEXTCLOUD_ADMIN_PASSWD%
    - DOMAIN=%CLOUD_DOMAIN%
    - DB_TYPE=mysql
    - DB_NAME=%DB_NEXTCLOUD%
    - DB_USER=%MYSQL_NEXTCLOUD_USER%
    - DB_PASSWORD=%MYSQL_NEXTCLOUD_PASSWD%
    - DB_HOST=dbnextcloud
  links:
    - dbnextcloud:dbnextcloud
  ports:
    - 8181:8888
  volumes:
    - ./dockers/nextcloud/data:/data
    - ./dockers/nextcloud/config:/config
    - ./dockers/nextcloud/apps:/apps
    - ./dockers/nextcloud/themes:/nextcloud/themes

#RuTorrent-rTorrent
rutorrent:
  image: diameter/rtorrent-rutorrent
  container_name: rutorrent
  environment:
    - WEBROOT=/
    - USR_ID=%UID%
    - GRP_ID=%GID%
  ports:
    - "8282:80"
    - "49160:49160/udp"
    - "49161:49161"
  volumes:
    - /downloads:/downloads

#Jackett
jackett:
  image : linuxserver/jackett
  container_name: jackett
  environment:
    - PGID=%UID%
    - PUID=%GID%
    - TZ=%TIMEZONE%
  ports:
    - 8383:9117
  volumes:
    - /etc/localtime:/etc/locatime:ro
    - ./dockers/jackett/downloads:/downloads

#Radarr
radarr:
  image: hotio/radarr
  container_name: radarr
  environment:
    - PUID=%UID%
    - PGID=%GID%
    - TZ=%TIMEZONE%
  ports:
    - 8484:7878
  links:
    - rutorrent:rutorrent
  volumes:
    - ./dockers/radarr/config:/config
    - /movie-downloads:/downloads
    - /movies:/movies

#Sonarr
sonarr:
  image: linuxserver/sonarr
  container_name: sonarr
  environment:
    - PUID=%UID%
    - PGID=%GID%
    - TZ=%TIMEZONE%
  ports:
    - 8585:8989
  links:
    - rutorrent:rutorrent
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./dockers/sonarr/config:/config
    - /tv-downloads:/downloads
    - /tv:/tv

#UI For Docker
ui-for-docker:
  image: uifd/ui-for-docker
  container_name: ui-for-docker
  ports:
    - 8686:9000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
